version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - rednet
    ports:
      - ${PORT}:${PORT}

networks:
  rednet:
    name: rednet
    external: true
